
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.COPY_ATTRIBUTES;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FLAVIO
 */
public class TelaInicial extends javax.swing.JFrame implements KeyListener {

    /**
     * Creates new form TelaInicial
     */
    String sexo;
    ImageIcon getIcon;
    BufferedImage setIcon;
    String caminho;
    String message;
    String atuChat = "";
    int limpaChat = 0;
    String ultimoChat = "";
    String maxId, minId;
    int limitIns = 0;
    
    public TelaInicial() {
        initComponents();
        paineis();
        chatReceber();
        new Thread(){
            public void run(){               
                while(true){
                    ultId();
                    ultChat();
                    atualChat();                   
                    atualizaChat();
                    }}
        }.start();
        chatVivo.setEditable(false);
        tratarEventos();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPerfil = new javax.swing.JPanel();
        perfilNome = new javax.swing.JLabel();
        perfilNascimento = new javax.swing.JLabel();
        perfilSexo = new javax.swing.JLabel();
        Upload = new javax.swing.JButton();
        imageIcon = new javax.swing.JLabel();
        painelEditar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        editNome = new javax.swing.JTextField();
        editSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        editDia = new javax.swing.JSpinner();
        editMes = new javax.swing.JSpinner();
        editAno = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        editFem = new javax.swing.JCheckBox();
        editMasc = new javax.swing.JCheckBox();
        editar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        excluir = new javax.swing.JButton();
        painelInicio = new javax.swing.JPanel();
        chatEnvio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatVivo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listOnline = new javax.swing.JList<>();
        menu = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuPerfil = new javax.swing.JMenu();
        menuEditar = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        perfilNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        perfilNascimento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        perfilSexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Upload.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Upload.setText("Carregar");
        Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadActionPerformed(evt);
            }
        });

        imageIcon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout painelPerfilLayout = new javax.swing.GroupLayout(painelPerfil);
        painelPerfil.setLayout(painelPerfilLayout);
        painelPerfilLayout.setHorizontalGroup(
            painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPerfilLayout.createSequentialGroup()
                .addGroup(painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelPerfilLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelPerfilLayout.createSequentialGroup()
                                .addGroup(painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(perfilSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(perfilNome, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE))
                            .addGroup(painelPerfilLayout.createSequentialGroup()
                                .addComponent(perfilNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painelPerfilLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Upload)
                        .addGap(22, 22, 22)))
                .addGap(42, 42, 42))
        );
        painelPerfilLayout.setVerticalGroup(
            painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPerfilLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(perfilNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(perfilSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPerfilLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(perfilNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPerfilLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(imageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addComponent(Upload)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Editar Credenciais");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Senha:");

        editNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        editSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Data de Nascimento:");

        editDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        editMes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        editAno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editAno.setModel(new javax.swing.SpinnerNumberModel(1890, 1890, 2021, 1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Sexo:");

        editFem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editFem.setText("Feminino");
        editFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFemActionPerformed(evt);
            }
        });

        editMasc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editMasc.setText("Masculino");
        editMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMascActionPerformed(evt);
            }
        });

        editar.setText("Confirmar");
        editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarMouseClicked(evt);
            }
        });
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Deseja Excluir sua conta?");

        excluir.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        excluir.setText("Sim");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelEditarLayout = new javax.swing.GroupLayout(painelEditar);
        painelEditar.setLayout(painelEditarLayout);
        painelEditarLayout.setHorizontalGroup(
            painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEditarLayout.createSequentialGroup()
                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEditarLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel2))
                    .addGroup(painelEditarLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelEditarLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(editSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelEditarLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(editNome, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelEditarLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(editDia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editMes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editAno, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelEditarLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(editFem)
                                .addGap(18, 18, 18)
                                .addComponent(editMasc))))
                    .addGroup(painelEditarLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(editar)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEditarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEditarLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEditarLayout.createSequentialGroup()
                        .addComponent(excluir)
                        .addGap(88, 88, 88))))
        );
        painelEditarLayout.setVerticalGroup(
            painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEditarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(editNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(editDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(editSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(editFem)
                    .addComponent(editMasc))
                .addGap(18, 18, 18)
                .addComponent(editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excluir)
                .addGap(22, 22, 22))
        );

        chatEnvio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chatEnvio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null));

        chatVivo.setColumns(20);
        chatVivo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        chatVivo.setRows(5);
        chatVivo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(chatVivo);

        listOnline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        listOnline.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(listOnline);

        javax.swing.GroupLayout painelInicioLayout = new javax.swing.GroupLayout(painelInicio);
        painelInicio.setLayout(painelInicioLayout);
        painelInicioLayout.setHorizontalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInicioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chatEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelInicioLayout.setVerticalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(painelInicioLayout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chatEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );

        menu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuInicio.setText("INICIO");
        menuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInicioMouseClicked(evt);
            }
        });
        menu.add(menuInicio);

        menuPerfil.setText("PERFIL");
        menuPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPerfilMouseClicked(evt);
            }
        });
        menu.add(menuPerfil);

        menuEditar.setText("EDITAR");
        menuEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEditarMouseClicked(evt);
            }
        });
        menu.add(menuEditar);

        menuSair.setText("SAIR");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuSairMouseExited(evt);
            }
        });
        menu.add(menuSair);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        // TODO add your handling code here:
        Main inicio = new Main();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseExited
        // TODO add your handling code here:
       menuSair.setBackground(Color.blue);
    }//GEN-LAST:event_menuSairMouseExited

    private void menuSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSairMouseEntered

    private void menuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInicioMouseClicked
        // TODO add your handling code here:        
        painelInicio.setVisible(true);
        painelPerfil.setVisible(false);
        painelEditar.setVisible(false);
        
    }//GEN-LAST:event_menuInicioMouseClicked

    private void menuPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPerfilMouseClicked
        // TODO add your handling code here:
        painelInicio.setVisible(false);
        painelPerfil.setVisible(true);
        painelEditar.setVisible(false);
        Identificador ident = new Identificador();
        getUploadPerfil();
        perfilNome.setText("Nome: "+ident.getNome());
        perfilNascimento.setText("Data de Nascimento: "+ident.getData());
        if(ident.getSexo().equals("F")){
            perfilSexo.setText("Genero: "+"Feminino");
        }else if(ident.getSexo().equals("M")){
            perfilSexo.setText("Genero: "+"Masculino");
        }        
    }//GEN-LAST:event_menuPerfilMouseClicked

    private void menuEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEditarMouseClicked
        // TODO add your handling code here:
        painelInicio.setVisible(false);
        painelPerfil.setVisible(false);
        painelEditar.setVisible(true);
    }//GEN-LAST:event_menuEditarMouseClicked

    private void editFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFemActionPerformed
        // TODO add your handling code here:
        sexo = "F";
        editMasc.setSelected(false);
        
    }//GEN-LAST:event_editFemActionPerformed

    private void editMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMascActionPerformed
        // TODO add your handling code here:
        sexo = "M";
        editFem.setSelected(false);
    }//GEN-LAST:event_editMascActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        Identificador logo = new Identificador();        
        String url = "jdbc:mysql://localhost/cadastro";
        String novoNome = editNome.getText();
        String novaSenha = editSenha.getText();
        int ano = (int) editAno.getValue();
        int mes = (int) editMes.getValue();
        int dia = (int) editDia.getValue();
        int ident = logo.getId();        
        ImageIcon image = new ImageIcon(setIcon);
        imageIcon.setIcon(image);
        String novoNascimento = ano+"-"+mes+"-"+dia;
        String update = "UPDATE pessoa SET nome='"+novoNome+"',senha='"+novaSenha+"',nascimento='"+novoNascimento+"',sexo='"+sexo+"' WHERE id="+ident+"";        
        try{
            Connection conect = (Connection) DriverManager.getConnection(url, "root", "");
            PreparedStatement atualiza = conect.prepareStatement(update);
            atualiza.executeUpdate();
            JOptionPane.showMessageDialog(null,"Credenciais alteradas com sucesso");
        }catch(Exception erro){
        }
    }//GEN-LAST:event_editarActionPerformed

    private void editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_editarMouseClicked

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        Identificador logo = new Identificador();        
        String url = "jdbc:mysql://localhost/cadastro";
        int idDelete = logo.getId();
        String delete = "DELETE FROM pessoa WHERE id="+idDelete;
        try{
            Connection conect = (Connection) DriverManager.getConnection(url,"root","");
            PreparedStatement del = conect.prepareStatement(delete);
            del.executeUpdate();
            JOptionPane.showMessageDialog(null,"Conta Excluida!");
            Main inicio = new Main();
            inicio.setVisible(true);
            dispose();
        }catch(Exception ERRO){
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadActionPerformed
        // TODO add your handling code here:
        Identificador logo = new Identificador();        
        getUpload();         
        int id = logo.getId();                
        String url = "jdbc:mysql://localhost/cadastro";
        String sql = "UPDATE pessoa SET caminho='"+caminho+"' WHERE id="+id;        
        try{
            Connection conect = (Connection) DriverManager.getConnection(url,"root","");
            PreparedStatement icon = conect.prepareStatement(sql);            
            icon.executeUpdate();           
        }catch(Exception ex){
        }
    }//GEN-LAST:event_UploadActionPerformed

    public void paineis(){
        painelInicio.setVisible(true);
        painelPerfil.setVisible(false);
        painelEditar.setVisible(false);               
    }
    public void getUpload(){
        Identificador logo = new Identificador();       
        JFileChooser fc = new JFileChooser();        
        int res = fc.showOpenDialog(null);
        if(res == JFileChooser.APPROVE_OPTION){
            File arquivo = fc.getSelectedFile();
            try {               
                setIcon = ImageIO.read(arquivo);                
                File setCaminho = new File("src/Imagem/"+arquivo.getName());
                while(setCaminho.exists() != false){
                    int numerador = 1;
                    File novCaminho = new File("src/Imagem"+arquivo.getName()+numerador);
                    numerador++;
                }
                Files.copy(Paths.get(arquivo.getAbsolutePath()), Paths.get(setCaminho.getPath()), COPY_ATTRIBUTES); 
                caminho = "Imagem>"+arquivo.getName();
                ImageIcon image = new ImageIcon(setIcon); 
                image.setImage(image.getImage().getScaledInstance(imageIcon.getWidth(), imageIcon.getHeight(), 1));
                imageIcon.setIcon(image);
            } catch (IOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }    
    public void getUploadPerfil(){
        Identificador ident = new Identificador();
        
        int ide = ident.getId();
        String url = "jdbc:mysql://localhost/cadastro";
        String sql = "SELECT caminho FROM pessoa WHERE id="+ide;
        try{
            Connection conect = (Connection) DriverManager.getConnection(url,"root","");
            PreparedStatement pesquisa = conect.prepareStatement(sql);
            ResultSet resultado = pesquisa.executeQuery();
            while(resultado.next()){
                String cam = resultado.getString("caminho");
                cam = cam.replaceAll(">", "/");                
                getIcon = new ImageIcon(getClass().getResource(cam));
                getIcon.setImage(getIcon.getImage().getScaledInstance(imageIcon.getWidth(), imageIcon.getHeight(), 1));
                imageIcon.setIcon(getIcon);
                break;
            }
        }catch(Exception e){
        }
    }
    public void chatEnviar(){
        Identificador ident = new Identificador();
        String nomeChat = ident.getNome();
        int idi = ident.getId();
        String getNome = nomeChat+" : ";
        String url = "jdbc:mysql://localhost/cadastro";
        String insert = "INSERT INTO chat(user, mensagem) values("+idi+",'"+getNome+message+"')";       
        try{
            Connection conect = (Connection) DriverManager.getConnection(url,"root","");
            PreparedStatement atualizar = conect.prepareStatement(insert);
            atualizar.executeUpdate();
        }catch(Exception e){
        }
    }
    public void ultId(){
        String url = "jdbc:mysql://localhost/cadastro";
        
        try{
            Connection conexao = (Connection) DriverManager.getConnection(url,"root","");
            PreparedStatement pesquisa = conexao.prepareStatement("SELECT max(id), min(id) FROM chat");
            ResultSet resultado = pesquisa.executeQuery();            
                while(resultado.next()){                    
                    maxId = resultado.getString("max(id)");
                    minId = resultado.getString("min(id)");
                    }
        }catch(Exception e){}
    }
    public void ultChat(){
        String url = "jdbc:mysql://localhost/cadastro";
        
        try{
            Connection conexao = (Connection) DriverManager.getConnection(url,"root","");
            PreparedStatement pesquisa = conexao.prepareStatement("SELECT mensagem FROM chat WHERE id="+maxId+"");
            ResultSet resultado = pesquisa.executeQuery();            
                while(resultado.next()){                    
                    ultimoChat = resultado.getString("mensagem");                   
                    }
        }catch(Exception e){}
    }
    public void chatReceber(){
        String url = "jdbc:mysql://localhost/cadastro";
        
        try{
            Connection conexao = (Connection) DriverManager.getConnection(url,"root","");
            PreparedStatement pesquisa = conexao.prepareStatement("SELECT mensagem FROM chat");
            ResultSet resultado = pesquisa.executeQuery();            
                            while(resultado.next()){
                                atuChat = resultado.getString("mensagem");                                
                                chatVivo.append(atuChat);
                                chatVivo.append("\n");
                                limpaChat++;                                                                
                }
        }catch(Exception e){
        }
    }
    public void atualChat(){
        if(!atuChat.equals(ultimoChat)){
                     atuChat = ultimoChat;
                     chatVivo.append(atuChat);
                     chatVivo.append("\n");
                     
                 }
    }
    public void atualizaChat(){
         String url = "jdbc:mysql://localhost/cadastro";
        
        try{
            Connection conexao = (Connection) DriverManager.getConnection(url,"root","");
            PreparedStatement pesquisa = conexao.prepareStatement("SELECT mensagem FROM chat");
            ResultSet resultado = pesquisa.executeQuery();
                 if(!atuChat.equals(ultimoChat)){
                     atuChat = ultimoChat;
                     chatVivo.append(atuChat);
                 }
        }catch(Exception e){
        }
    }
    public void chatClear(){
        String url = "jdbc:mysql://localhost/cadastro";
        if(limpaChat >= 50){
             try{
            Connection conect = (Connection) DriverManager.getConnection(url,"root","");
            PreparedStatement del = conect.prepareStatement("");
            del.executeUpdate();
             }catch(Exception e){
            }
        }
    }
    private void tratarEventos(){
        

        chatEnvio.addKeyListener(new KeyListener() {
            Identificador ident = new Identificador();
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
                                
               
                
            }
            @Override
            public void keyReleased(KeyEvent e) {
                if(e.getKeyCode() == KeyEvent.VK_ENTER){
                   message = chatEnvio.getText();                   
                   chatEnviar();                                     
                if(chatVivo.getText().isEmpty()){
                    return;
                }
                chatEnvio.setText("");
                }
            }
        });
    }           
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        TelaInicial cli = new TelaInicial();
        
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Upload;
    private javax.swing.JTextField chatEnvio;
    private javax.swing.JTextArea chatVivo;
    private javax.swing.JSpinner editAno;
    private javax.swing.JSpinner editDia;
    private javax.swing.JCheckBox editFem;
    private javax.swing.JCheckBox editMasc;
    private javax.swing.JSpinner editMes;
    private javax.swing.JTextField editNome;
    private javax.swing.JPasswordField editSenha;
    private javax.swing.JButton editar;
    private javax.swing.JButton excluir;
    public javax.swing.JLabel imageIcon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listOnline;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuPerfil;
    private javax.swing.JMenu menuSair;
    private javax.swing.JPanel painelEditar;
    public javax.swing.JPanel painelInicio;
    public javax.swing.JPanel painelPerfil;
    private javax.swing.JLabel perfilNascimento;
    private javax.swing.JLabel perfilNome;
    private javax.swing.JLabel perfilSexo;
    // End of variables declaration//GEN-END:variables

    private String toString(int id) {
        
        return null;
        
    }

    @Override
    public void keyTyped(KeyEvent e) {
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
        
    }

    @Override
    public void keyReleased(KeyEvent e) {
        
    }
}
